/**
 * Display text for the option lists in lib/forms.
 *
 * Those lists are configuration: the English value is what gets stored,
 * routed and quoted to the pharmacist, so it never changes with the language.
 * This is only what the person reads. Keyed on the English text; anything not
 * listed shows as it is.
 */
import { defineStrings, translate } from '@/i18n';

const S = defineStrings({
  en: {
    'Ordered by mistake': 'Ordered by mistake',
    'Delivery is taking too long': 'Delivery is taking too long',
    'Found it cheaper elsewhere': 'Found it cheaper elsewhere',
    'I no longer need it': 'I no longer need it',
    'Something else': 'Something else',
    'Damaged on arrival': 'Damaged on arrival',
    'Wrong item sent': 'Wrong item sent',
    'Missing from the order': 'Missing from the order',
    'Expired or close to expiry': 'Expired or close to expiry',
    'Privacy concerns': 'Privacy concerns',
    'Delivery was too slow': 'Delivery was too slow',
    'I use another pharmacy': 'I use another pharmacy',
    'Something is missing from my order': 'Something is missing from my order',
    'An item was not delivered': 'An item was not delivered',
    'I received the wrong item': 'I received the wrong item',
    'Different medicine or strength': 'Different medicine or strength',
    'The item arrived damaged': 'The item arrived damaged',
    'Broken seal, crushed box, leaking': 'Broken seal, crushed box, leaking',
    'The delivery never arrived': 'The delivery never arrived',
    'Marked delivered but not received': 'Marked delivered but not received',
    'A billing or payment problem': 'A billing or payment problem',
    'Charged twice, wrong amount': 'Charged twice, wrong amount',
    'Refund initiated': 'Refund initiated',
    'Just now': 'Just now',
    'Sent to Paystack': 'Sent to Paystack',
    'Within 1 hour': 'Within 1 hour',
    'Back on your card': 'Back on your card',
    '3–5 business days': '3–5 business days',
  },
  fr: {
    'Ordered by mistake': 'Commandé par erreur',
    'Delivery is taking too long': 'La livraison prend trop de temps',
    'Found it cheaper elsewhere': 'Trouvé moins cher ailleurs',
    'I no longer need it': "Je n'en ai plus besoin",
    'Something else': 'Autre chose',
    'Damaged on arrival': 'Endommagé à la livraison',
    'Wrong item sent': 'Mauvais article envoyé',
    'Missing from the order': 'Manquant dans la commande',
    'Expired or close to expiry': 'Périmé ou presque périmé',
    'Privacy concerns': 'Confidentialité',
    'Delivery was too slow': 'Livraison trop lente',
    'I use another pharmacy': "J'utilise une autre pharmacie",
    'Something is missing from my order': 'Il manque quelque chose dans ma commande',
    'An item was not delivered': "Un article n'a pas été livré",
    'I received the wrong item': "J'ai reçu le mauvais article",
    'Different medicine or strength': 'Autre médicament ou autre dosage',
    'The item arrived damaged': "L'article est arrivé endommagé",
    'Broken seal, crushed box, leaking': 'Scellé cassé, boîte écrasée, fuite',
    'The delivery never arrived': "La livraison n'est jamais arrivée",
    'Marked delivered but not received': 'Indiquée livrée mais non reçue',
    'A billing or payment problem': 'Un problème de facturation ou de paiement',
    'Charged twice, wrong amount': 'Débité deux fois, mauvais montant',
    'Refund initiated': 'Remboursement lancé',
    'Just now': "À l'instant",
    'Sent to Paystack': 'Envoyé à Paystack',
    'Within 1 hour': "Dans l'heure",
    'Back on your card': 'De retour sur votre carte',
    '3–5 business days': '3 à 5 jours ouvrés',
  },
  tw: {
    'Ordered by mistake': 'Metoɔ no mfomsoɔ mu',
    'Delivery is taking too long': 'Ɛde bere tenten dodo reba',
    'Found it cheaper elsewhere': 'Mahunu bi a ne boɔ yɛ fo wɔ baabi',
    'I no longer need it': 'Menhia bio',
    'Something else': 'Biribi foforɔ',
    'Damaged on arrival': 'Ɛsɛe ansa na ɛreba',
    'Wrong item sent': 'Wɔde adeɛ a ɛnyɛ no na ɛbaeɛ',
    'Missing from the order': 'Ɛnni deɛ metoɔ no mu',
    'Expired or close to expiry': 'Ne bere atwam anaa ɛreyɛ atwam',
    'Privacy concerns': 'Kokoam nsɛm ho dadwen',
    'Delivery was too slow': 'Ɛbaeɛ no kyɛreeɛ dodo',
    'I use another pharmacy': 'Mede nnuro dwam foforɔ di dwuma',
    'Something is missing from my order': 'Biribi nni deɛ metoɔ no mu',
    'An item was not delivered': 'Wɔamfa adeɛ baako amma',
    'I received the wrong item': 'Mennyaa adeɛ a ɛfata',
    'Different medicine or strength': 'Aduro foforɔ anaa ne mmirika nsɛ',
    'The item arrived damaged': 'Adeɛ no sɛeɛ ansa na ɛduruiɛ',
    'Broken seal, crushed box, leaking': 'Ano abue, adaka no apɛ, ɛreguo',
    'The delivery never arrived': 'Adeɛ no amma koraa',
    'Marked delivered but not received': 'Wɔse ɛbaeɛ nanso mennyaeɛ',
    'A billing or payment problem': 'Ka tua mu haw',
    'Charged twice, wrong amount': 'Wɔgyee mprenu, sika dodoɔ a ɛnteɛ',
    'Refund initiated': 'Sika sanba ahyɛ aseɛ',
    'Just now': 'Seesei ara',
    'Sent to Paystack': 'Wɔde akɔma Paystack',
    'Within 1 hour': 'Dɔnhwere 1 mu',
    'Back on your card': 'Asan aba wo kaad so',
    '3–5 business days': 'Adwuma nna 3–5',
  },
  gaa: {
    'Ordered by mistake': 'Mihe yɛ tɔmɔ mli',
    'Delivery is taking too long': 'Ebaa lɛ miiŋɔ be babaoo',
    'Found it cheaper elsewhere': 'Miná ni ejara bɛ yɛ he kroko',
    'I no longer need it': 'Mihiaaa dɔŋŋ',
    'Something else': 'Nɔ kroko',
    'Damaged on arrival': 'Efite dani eba',
    'Wrong item sent': 'Akɛ nɔ ni ejaaa ba',
    'Missing from the order': 'Ebɛ nɔ ni mihe lɛ mli',
    'Expired or close to expiry': 'Ebe ho loo ebe miiho',
    'Privacy concerns': 'Teemɔŋ saji he gbeyei',
    'Delivery was too slow': 'Ebaa lɛ sɛɛ tee',
    'I use another pharmacy': 'Mikɛ tsofa shĩa kroko tsuɔ nii',
    'Something is missing from my order': 'Nɔ ko bɛ nɔ ni mihe lɛ mli',
    'An item was not delivered': 'Akɛ nɔ kome baaa',
    'I received the wrong item': 'Miná nɔ ni ejaaa',
    'Different medicine or strength': 'Tsofa kroko loo ehewalɛ kroko',
    'The item arrived damaged': 'Nɔ lɛ fite dani eba',
    'Broken seal, crushed box, leaking': 'Enaa egbɛ, adeka lɛ fite, eŋmɛɔ',
    'The delivery never arrived': 'Nɔ lɛ baaa kwraa',
    'Marked delivered but not received': 'Akɛɛ eba shi minááá',
    'A billing or payment problem': 'Nyɔmɔwoo he naagba',
    'Charged twice, wrong amount': 'Ahe shika shii enyɔ, shika ni ejaaa',
    'Refund initiated': 'Shika ni aaaku asɛɛ lɛ je shishi',
    'Just now': 'Bianɛ nɔŋŋ',
    'Sent to Paystack': 'Akɛtee Paystack',
    'Within 1 hour': 'Ŋmɛlɛtswaa 1 mli',
    'Back on your card': 'Eku esɛɛ kɛba o kaad nɔ',
    '3–5 business days': 'Nitsumɔ gbii 3–5',
  },
  ee: {
    'Ordered by mistake': 'Meɖee le vodada me',
    'Delivery is taking too long': 'Eƒe vava le ɣeyiɣi didi xɔm akpa',
    'Found it cheaper elsewhere': 'Mekpɔe le teƒe bubu kple asi si le bɔbɔe',
    'I no longer need it': 'Nyemehiãe azɔ o',
    'Something else': 'Nu bubu',
    'Damaged on arrival': 'Egblẽ hafi va ɖo',
    'Wrong item sent': 'Wodɔ nu si menye o',
    'Missing from the order': 'Mele nudodo la me o',
    'Expired or close to expiry': 'Eƒe ɣeyiɣi va yi alo ele yiyim',
    'Privacy concerns': 'Nya ɣaɣlawo ŋuti tamebubu',
    'Delivery was too slow': 'Eƒe vava tsi megbe akpa',
    'I use another pharmacy': 'Mezãa atikedzraƒe bubu',
    'Something is missing from my order': 'Nane mele nye nudodo me o',
    'An item was not delivered': 'Womekplɔ nu ɖeka va o',
    'I received the wrong item': 'Mexɔ nu si menye o',
    'Different medicine or strength': 'Atike bubu alo ŋusẽ bubu',
    'The item arrived damaged': 'Nu la gblẽ hafi va ɖo',
    'Broken seal, crushed box, leaking': 'Nutre la ʋu, agba la gblẽ, ele tsyɔm',
    'The delivery never arrived': 'Nu la meva kura o',
    'Marked delivered but not received': 'Wogblɔ be eva gake nyemexɔe o',
    'A billing or payment problem': 'Fexexe ŋuti kuxi',
    'Charged twice, wrong amount': 'Woxɔ ga zi eve, ga si mesɔ o',
    'Refund initiated': 'Gatrɔtrɔ dze egɔme',
    'Just now': 'Fifia ko',
    'Sent to Paystack': 'Woɖoe ɖe Paystack',
    'Within 1 hour': 'Le gaƒoƒo 1 me',
    'Back on your card': 'Egbɔ va wò kaad dzi',
    '3–5 business days': 'Dɔwɔŋkeke 3–5',
  },
  ha: {
    'Ordered by mistake': 'Na yi oda bisa kuskure',
    'Delivery is taking too long': 'Kawowa na ɗaukar lokaci mai tsawo',
    'Found it cheaper elsewhere': 'Na samu mai rahusa a wani wuri',
    'I no longer need it': 'Ban ƙara buƙata ba',
    'Something else': 'Wani abu daban',
    'Damaged on arrival': 'Ya lalace kafin ya iso',
    'Wrong item sent': 'An aiko kayan da ba daidai ba',
    'Missing from the order': 'Ba ya cikin odar',
    'Expired or close to expiry': 'Ya ƙare ko yana gab da ƙarewa',
    'Privacy concerns': 'Damuwa game da sirri',
    'Delivery was too slow': 'Kawowa ta yi jinkiri sosai',
    'I use another pharmacy': 'Ina amfani da wani kantin magani',
    'Something is missing from my order': 'Akwai abin da ya ɓace a odata',
    'An item was not delivered': 'Ba a kawo wani kaya ba',
    'I received the wrong item': 'Na karɓi kayan da ba daidai ba',
    'Different medicine or strength': 'Wani magani daban ko ƙarfi daban',
    'The item arrived damaged': 'Kayan ya iso a lalace',
    'Broken seal, crushed box, leaking': 'Hatimi ya karye, akwati ya matse, yana zuba',
    'The delivery never arrived': 'Kayan bai iso ba ko kaɗan',
    'Marked delivered but not received': 'An ce an kawo amma ban karɓa ba',
    'A billing or payment problem': 'Matsalar biya',
    'Charged twice, wrong amount': 'An caje sau biyu, adadin ba daidai ba',
    'Refund initiated': 'An fara mayar da kuɗi',
    'Just now': 'Yanzu-yanzu',
    'Sent to Paystack': 'An tura zuwa Paystack',
    'Within 1 hour': 'Cikin awa 1',
    'Back on your card': 'Ya dawo katinka',
    '3–5 business days': 'Kwanakin aiki 3–5',
  },
});

type Key = keyof (typeof S)['en'];

/** What to show for a form option whose stored value is `english`. */
export function formLabel(english: string): string {
  return english in S.en ? translate(S, english as Key) : english;
}

const STEPS = defineStrings({
  en: {
    received: 'Request received',
    receivedMeta: 'Altruist passed it to the pharmacy · {at}',
    reviewing: 'Pharmacy reviewing',
    reviewingMeta: '{pharmacy} · usually within 2 business days',
    decision: 'Decision',
    decisionMeta: 'Approved in full, in part, or declined with a reason',
    back: 'Money back on your card',
    backMeta: '3–5 business days after approval',
  },
  fr: {
    received: 'Demande reçue',
    receivedMeta: "Altruist l'a transmise à la pharmacie · {at}",
    reviewing: 'Examen par la pharmacie',
    reviewingMeta: '{pharmacy} · généralement sous 2 jours ouvrés',
    decision: 'Décision',
    decisionMeta: 'Acceptée en totalité, en partie, ou refusée avec un motif',
    back: 'Argent de retour sur votre carte',
    backMeta: "3 à 5 jours ouvrés après l'accord",
  },
  tw: {
    received: 'Yɛanya wo abisadeɛ',
    receivedMeta: 'Altruist de akɔma nnuro dwam no · {at}',
    reviewing: 'Nnuro dwam no rehwɛ mu',
    reviewingMeta: '{pharmacy} · mpɛn pii adwuma nna 2 mu',
    decision: 'Gyinaeɛ',
    decisionMeta: 'Wɔagye nyinaa, ɛfa, anaa wɔapo na wɔaka deɛ ɛma',
    back: 'Sika asan aba wo kaad so',
    backMeta: 'Adwuma nna 3–5 wɔ gyinaeɛ akyi',
  },
  gaa: {
    received: 'Wɔná o bimɔ lɛ',
    receivedMeta: 'Altruist kɛtee tsofa shĩa lɛ · {at}',
    reviewing: 'Tsofa shĩa lɛ miikwɛ mli',
    reviewingMeta: '{pharmacy} · yɛ nitsumɔ gbii 2 mli',
    decision: 'Yiŋkpɛɛmɔ',
    decisionMeta: 'Akpɛlɛ nɔ fɛɛ, fã, loo akpoo kɛ nɔ hewɔ',
    back: 'Shika eku esɛɛ kɛba o kaad nɔ',
    backMeta: 'Nitsumɔ gbii 3–5 yɛ kpɛlɛmɔ sɛɛ',
  },
  ee: {
    received: 'Míexɔ wò biabia',
    receivedMeta: 'Altruist tsɔe ɖo ɖe atikedzraƒe la · {at}',
    reviewing: 'Atikedzraƒe la le edzi kpɔm',
    reviewingMeta: '{pharmacy} · zi geɖe le dɔwɔŋkeke 2 me',
    decision: 'Nyametsotso',
    decisionMeta: 'Woxɔe blibo, ƒe akpa aɖe, alo wogbee kple susu',
    back: 'Ga gbɔ va wò kaad dzi',
    backMeta: 'Dɔwɔŋkeke 3–5 le nyametsotso megbe',
  },
  ha: {
    received: 'An karɓi buƙatarka',
    receivedMeta: 'Altruist ya tura shi ga kantin magani · {at}',
    reviewing: 'Kantin magani yana dubawa',
    reviewingMeta: '{pharmacy} · yawanci cikin kwanakin aiki 2',
    decision: 'Hukunci',
    decisionMeta: 'An amince gaba ɗaya, wani ɓangare, ko an ƙi da dalili',
    back: 'Kuɗi ya dawo katinka',
    backMeta: 'Kwanakin aiki 3–5 bayan amincewa',
  },
});

/** Titles and notes for the post-delivery refund timeline, in the current language. */
export function refundStepText(pharmacyName: string, raisedAt: string) {
  const t = (key: keyof (typeof STEPS)['en'], vars?: Record<string, string>) =>
    translate(STEPS, key, vars);
  return [
    { title: t('received'), meta: t('receivedMeta', { at: raisedAt }) },
    { title: t('reviewing'), meta: t('reviewingMeta', { pharmacy: pharmacyName }) },
    { title: t('decision'), meta: t('decisionMeta') },
    { title: t('back'), meta: t('backMeta') },
  ];
}
